version: 2
jobs:
  git-check:
    docker:
      - image: hashicorp/packer:1.4.0
    steps:
      - checkout
      - run:
          name: Test
          command: |
              ls -lsah .circleci
              .circleci/kill.sh aws/packer
  validate:
    docker:
      - image: hashicorp/packer:1.4.0
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Setup AWS credentials
          command: mkdir ~/.aws; echo -e "[default]\naws_access_key_id=$AWS_ACCESS_KEY_ID_PROD\naws_secret_access_key=$AWS_SECRET_ACCESS_KEY_PROD\n" > ~/.aws/credentials
      - run:
          working_directory: ~/packer/aws/packer
          name: Validate base
          command: packer validate -var-file=variables.json build.json
  build:
    docker:
      - image: hashicorp/packer:1.4.0
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Setup AWS credentials
          command: mkdir ~/.aws; echo -e "[default]\naws_access_key_id=$AWS_ACCESS_KEY_ID_PROD\naws_secret_access_key=$AWS_SECRET_ACCESS_KEY_PROD\n" > ~/.aws/credentials
      - run:
          working_directory: ~/packer/aws/packer
          no_output_timeout: 45m
          name: Build base
          command: packer build -var-file=variables.json build.json

workflows:
  version: 2
  deploy:
    jobs:
      - validate
      - build:
          requires:
            - validate
