version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/packer:1.4.0
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: git-check
          command: |
              .circleci/kill.sh aws/packer
      - run:
          working_directory: ~/packer/aws/packer
          name: Validate base
          command: packer validate -var-file=variables.json build.json
  build:
    docker:
      - image: hashicorp/packer:1.4.0
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          working_directory: ~/packer/aws/packer
          no_output_timeout: 45m
          name: Build base
          command: packer build -var-file=variables.json build.json

workflows:
  version: 2
  deploy:
    jobs:
      - validate
      - build:
          requires:
            - validate
